# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "News"
  url = "post"
  weight = 20

[[main]]
  identifier = "group"
  name = "People"
  url = "people"
  weight = 30

[[main]]
  name = "Prof. Kulik"
  url = "author/prof.-heather-j.-kulik"
  parent = "group"
  weight = 10

[[main]]
  name = "Group Members"
  url = "people"
  parent = "group"
  weight = 20
#[[main]]
#  name = "Events"
#  url = "event"
#  weight = 40
[[main]]
  name = "Tutorials"
  url = "tutorials"
  weight = 35


[[main]]
  name = "molSimplify"
  url = "https://molsimplify.mit.edu"
  weight = 40

[[main]]
  identifier = "pubs"
  name = "Publications"
  url = "publication"
  weight = 50

# Add submenus to the Publication page for different categories
# These menus work but sublocations on pub page don't exist --AHS
# [[main]]
#   parent = "pubs"
#   name = "Submitted"
#   url = "publication"
#   weight = 10
#
# [[main]]
#     parent = "pubs"
#     name = "In Press"
#     url = "publication"
#     weight = 20
#
# [[main]]
#     parent = "pubs"
#     name = "All"
#     url = "publication"
#     weight = 30

[[main]]
  name = "Contact"
  url = "contact"
  weight = 60
